/*


*/
//==============================================================================
//------------------------------------------------------------------------------
//==============================================================================

//DEFINICJE GRACZY


//==============================================================================
//-------------------- DEFINICJE GRACZY ----------------------------------------
//==============================================================================
#define DB_HIGHSKILL  "HighSkill/HighSkill.db"


#define T_KONTA				"a"

#define TK_ID				"b"
#define TK_NICK				"c"
#define TK_HASLO			"d"
#define TK_ALVL				"e"
#define TK_AHASLO			"f"
#define TK_ADATA			"g"
#define	TK_OST_LOGINS		"h"
#define	TK_OST_LOGIN_DATA	"i"
#define TK_OST_LOGIN_IP		"j"
#define	TK_DEL_KONTO		"k"
#define TK_OST_ZNICKU		"l"
#define TK_OST_NICK			"m"
#define TK_ZAUFANY			"n"
#define TK_WAR_ZAUFANY		"o"
#define TK_BAN_DATA			"p"
#define TK_BAN_ADMIN		"r"
#define TK_BAN_POWOD		"s"
#define TK_FRAGI			"t"
#define TK_SMIERCI			"u"
#define TK_RESPECT			"w"
#define TK_DMG				"x"
#define TK_W_SOLOWEK		"y"
#define TK_P_SOLOWEK		"z"
#define TK_Z_KASTET			"aa"
#define TK_Z_GRANATY		"ab"
#define TK_Z_SLP			"ac"
#define TK_Z_DE				"ad"
#define TK_Z_SG				"ae"
#define TK_Z_CSG			"af"
#define TK_Z_MP5			"ag"
#define TK_Z_AK47			"ah"
#define TK_Z_M4				"ai"
#define TK_Z_RIF			"aj"
#define TK_Z_SRIF			"ak"
#define TK_USTAWIENIA		"al"



#define T_BAN_HOST			"aa"

#define TBH_HOST			"ab"
#define TBH_DATA			"ac"
#define TBH_ADMIN			"ad"
#define TBH_POWOD			"ae"
#define TBH_IDGRACZA		"af"
#define	TBH_NAZWAGRACZA		"ag"



#define T_GRACZ_INFO		"aaa"

#define TGI_IP				"aab"
#define TGI_NICK			"aac"
#define TGI_DATA			"aad"
#define TGI_ZAREJESTROWANY	"aae"



#define T_USTAWIENIA		"aaaa"

#define TU_PING				"aaab"
#define TU_FPS				"aaac"
#define TU_CZAS_AREN		"aaad"
#define TU_CZAS_BAZ			"aaae"
#define TU_SLP				"aaaf"
#define TU_DE				"aaag"
#define TU_SG				"aaah"
#define TU_MP5				"aaai"
#define TU_AK47				"aaaj"
#define TU_M4				"aaak"
#define TU_RIF				"aaal"
#define TU_SRIF				"aaam"
#define	TU_ANTYGLITCH		"aaan"
#define TU_OGLOSZENIE		"aaao"
#define TU_OGLOSZENIE_DATA	"aaap"
#define	TU_MAX_ARMOU		"aaar"
#define	TU_DOD_GRANAT		"aaas"
#define TU_CZAS_TDM			"aaat"
#define TU_LIMIT_TDM		"aaau"



#define	T_RESET_KONT		"aaaaa"

#define	TRK_DATA			"aaaab"
#define	TRK_GRACZE			"aaaad"
#define	TRK_FRAGI			"aaaae"
#define	TRK_SMIERCI			"aaaaf"
#define	TRK_RESPEKT			"aaaag"
#define	TRK_DMG				"aaaah"



#define T_REKLAMA 				"aaaaaa"

#define TR_ID       			"aaaaab"
#define TR_NAZWA				"aaaaac"
#define TR_SCIEZKA     			"aaaaad"
#define TR_ODSLON_AKTUALNIE		"aaaaae"
#define TR_ODSLON_MAKSYMALNIE	"aaaaaf"
#define TR_ODSLON_LACZNIE  		"aaaaag"


#define T_BLACK_LIST			"aaaaaa"

#define TBL_NAGLOWEK			"aaaaab"
#define	TBL_DATA_WPISU			"aaaaac"
#define TBL_CZAS				"aaaaad"
#define TBL_ADMIN				"aaaaae"
#define TBL_POWOD				"aaaaaf"
